name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3d-printer-suite
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '3d-printer-suite/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 3d-printer-suite/yarn.lock

      - name: navigate to cwd
        run: cd 3d-printer-suite 
  
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: SPA fallback (copy index.html to 404.html)
        run: cp dist/index.html dist/404.html || true

      - name: Copy dist contents to root for GitHub Pages
        run: |
          # Go back to root directory
          cd ..
          # Copy all contents from 3d-printer-suite/dist to root
          cp -r 3d-printer-suite/dist/* .
          # Ensure .nojekyll is in root
          touch .nojekyll
          # Create 404.html for SPA fallback
          cp index.html 404.html || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


